name: Notify on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'New commit in {{ github.repository }}'
        body: 'A new commit has been pushed by {{ github.actor }}. View it at {{ github.event.head_commit.url }}'
        to: collaborator1@example.com,collaborator2@example.com
        from: ${{ secrets.EMAIL_USERNAME }}
